title: Gigachad
description: > # this means to ignore newlines until "baseurl:"
  Hackers in the Bazaar Blogs.
permalink: ':title/'
baseurl: "/gigachad" # the subpath of your site, e.g. /blog
url: "http://sambattalio.github.io" # <link rel="stylesheet" href="{{ root_url }}/css/main.css">the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sam Battalio # add your name
author-img: sam.jpg # add your photo
about-author: I am a Senior @ ND.
social-twitter: Colts # add your Twitter handle
social-facebook: none # add your Facebook handle
social-github: sambattalio # add your Github handle
social-linkedin: samuelbattalio # add your Linkedin handle
social-email: sam@gigachad.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
